# Generated by Django 3.0 on 2020-04-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.IntegerField(max_length=30)),
                ('province_name', models.CharField(max_length=70)),
                ('latitude_prov', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_prov', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
