# Generated by Django 3.0 on 2020-04-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kppdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='province_id',
            field=models.IntegerField(),
        ),
    ]
