# Generated by Django 3.0 on 2020-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kppdata', '0002_auto_20200424_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbperson',
            name='personid',
            field=models.IntegerField(null=True),
        ),
    ]
